services:
  sing-box:
    image: ghcr.io/sagernet/sing-box
    container_name: sing-box
    restart: unless-stopped
    ports:
      - 443:443
    volumes:
      - ./config:/etc/sing-box/
    command: >
      -D /var/lib/sing-box
      -C /etc/sing-box/inbounds/trojan
      -C /etc/sing-box/shared
      -C /etc/sing-box/warp
      run